# Data Basics Notebook
This notebook provides an introduction to working with both the Transfermarkt API
and UnderstatAPIs.

In [1]:
import duckdb
from understatapi import UnderstatClient
from matplotlib import pyplot as plt
import pandas as pd

## Transfermarkt API

In [3]:
# Example: Liverpool players from 2025
q = """
SELECT *
FROM read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/players.csv.gz') P
WHERE current_club_domestic_competition_id = 'GB1' AND last_season = 2025
AND P.current_club_id = 31
"""

duckdb.sql(q).show() # Run the query

┌───────────┬────────────┬──────────────┬─────────────────────┬─────────────┬─────────────────┬─────────────────────┬───────────────────────┬────────────────────┬────────────────────────┬─────────────────────┬────────────────────┬────────────┬─────────┬──────────────┬──────────────────────────┬───────────────────┬────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬─────────────────────────┬─────────────────────┬─────────────────────────────┐
│ player_id │ first_name │  last_name   │        name         │ last_season │ current_club_id │     player_code     │   country_of_birth    │   city_of_birth    │ country_of_citizenship │    date_of_birth    │    sub_position    │  position  │  foot   │ height_in_cm │ contract_expiration_date │    agent_name     │                                     image_url                                      │                                    url                                    │ current_club_domestic_competition_id │    current_club_name    │ market_value_in_eur │ highest_market_value_in_eur │
│   int64   │  varchar   │   varchar    │       varchar       │    int64    │      int64      │       varchar       │        varchar        │      varchar       │        varchar         │      timestamp      │      varchar       │  varchar   │ varchar │    int64     │        timestamp         │      varchar      │                                      varchar                                       │                                  varchar                                  │               varchar                │         varchar         │        int64        │            int64            │
├───────────┼────────────┼──────────────┼─────────────────────┼─────────────┼─────────────────┼─────────────────────┼───────────────────────┼────────────────────┼────────────────────────┼─────────────────────┼────────────────────┼────────────┼─────────┼──────────────┼──────────────────────────┼───────────────────┼────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼─────────────────────────┼─────────────────────┼─────────────────────────────┤
│    105470 │ NULL       │ Alisson      │ Alisson             │        2025 │              31 │ alisson             │ Brazil                │ Novo Hamburgo      │ Brazil                 │ 1992-10-02 00:00:00 │ Goalkeeper         │ Goalkeeper │ right   │          193 │ 2027-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/105470-1668522221.jpg?lm=1  │ https://www.transfermarkt.co.uk/alisson/profil/spieler/105470             │ GB1                                  │ Liverpool Football Club │            17000000 │                    90000000 │
│    139208 │ Virgil     │ van Dijk     │ Virgil van Dijk     │        2025 │              31 │ virgil-van-dijk     │ Netherlands           │ Breda              │ Netherlands            │ 1991-07-08 00:00:00 │ Centre-Back        │ Defender   │ right   │          195 │ 2027-06-30 00:00:00      │ ROOF              │ https://img.a.transfermarkt.technology/portrait/header/139208-1702049837.jpg?lm=1  │ https://www.transfermarkt.co.uk/virgil-van-dijk/profil/spieler/139208     │ GB1                                  │ Liverpool Football Club │            18000000 │                   100000000 │
│    146310 │ Wataru     │ Endo         │ Wataru Endo         │        2025 │              31 │ wataru-endo         │ Japan                 │ Yokohama, Kanagawa │ Japan                  │ 1993-02-09 00:00:00 │ Defensive Midfield │ Midfield   │ right   │          178 │ 2027-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/146310-1657181542.jpg?lm=1  │ https://www.transfermarkt.co.uk/wataru-endo/profil/spieler/146310         │ GB1                                  │ Liverpool Football Club │             5000000 │                    13000000 │
│    148455 │ Mohamed    │ Salah        │ Mohamed Salah       │        2025 │              31 │ mohamed-salah       │ Egypt                 │ Nagrig, Basyoun    │ Egypt                  │ 1992-06-15 00:00:00 │ Right Winger       │ Attack     │ left    │          175 │ 2027-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/148455-1727337594.jpg?lm=1  │ https://www.transfermarkt.co.uk/mohamed-salah/profil/spieler/148455       │ GB1                                  │ Liverpool Football Club │            30000000 │                   150000000 │
│    226049 │ Freddie    │ Woodman      │ Freddie Woodman     │        2025 │              31 │ freddie-woodman     │ England               │ London             │ England                │ 1997-03-04 00:00:00 │ Goalkeeper         │ Goalkeeper │ right   │          188 │ 2026-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/226049-1737883837.jpg?lm=1  │ https://www.transfermarkt.co.uk/freddie-woodman/profil/spieler/226049     │ GB1                                  │ Liverpool Football Club │             3000000 │                    10000000 │
│    256178 │ Joe        │ Gomez        │ Joe Gomez           │        2025 │              31 │ joe-gomez           │ England               │ London             │ England                │ 1997-05-23 00:00:00 │ Centre-Back        │ Defender   │ right   │          188 │ 2027-06-30 00:00:00      │ Wasserman         │ https://img.a.transfermarkt.technology/portrait/header/256178-1746645094.jpg?lm=1  │ https://www.transfermarkt.co.uk/joe-gomez/profil/spieler/256178           │ GB1                                  │ Liverpool Football Club │            15000000 │                    42000000 │
│    341092 │ Federico   │ Chiesa       │ Federico Chiesa     │        2025 │              31 │ federico-chiesa     │ Italy                 │ Genova             │ Italy                  │ 1997-10-25 00:00:00 │ Right Winger       │ Attack     │ right   │          175 │ 2028-06-30 00:00:00      │ LIAN Sports Group │ https://img.a.transfermarkt.technology/portrait/header/341092-1663576975.jpg?lm=1  │ https://www.transfermarkt.co.uk/federico-chiesa/profil/spieler/341092     │ GB1                                  │ Liverpool Football Club │            18000000 │                    65000000 │
│    357119 │ Ibrahima   │ Konaté       │ Ibrahima Konaté     │        2025 │              31 │ ibrahima-konate     │ France                │ Paris              │ France                 │ 1999-05-25 00:00:00 │ Centre-Back        │ Defender   │ right   │          194 │ 2026-06-30 00:00:00      │ CAA Stellar       │ https://img.a.transfermarkt.technology/portrait/header/357119-1669190550.jpg?lm=1  │ https://www.transfermarkt.co.uk/ibrahima-konate/profil/spieler/357119     │ GB1                                  │ Liverpool Football Club │            50000000 │                    50000000 │
│    433188 │ Curtis     │ Jones        │ Curtis Jones        │        2025 │              31 │ curtis-jones        │ England               │ Liverpool          │ England                │ 2001-01-30 00:00:00 │ Central Midfield   │ Midfield   │ right   │          185 │ 2027-06-30 00:00:00      │ Wasserman         │ https://img.a.transfermarkt.technology/portrait/header/433188-1701681163.jpg?lm=1  │ https://www.transfermarkt.co.uk/curtis-jones/profil/spieler/433188        │ GB1                                  │ Liverpool Football Club │            40000000 │                    40000000 │
│    434675 │ Cody       │ Gakpo        │ Cody Gakpo          │        2025 │              31 │ cody-gakpo          │ Netherlands           │ Eindhoven          │ Netherlands            │ 1999-05-07 00:00:00 │ Left Winger        │ Attack     │ right   │          193 │ 2030-06-30 00:00:00      │ SEG               │ https://img.a.transfermarkt.technology/portrait/header/434675-1682690965.jpg?lm=1  │ https://www.transfermarkt.co.uk/cody-gakpo/profil/spieler/434675          │ GB1                                  │ Liverpool Football Club │            70000000 │                    70000000 │
│       ·   │  ·         │   ·          │     ·               │          ·  │               · │     ·               │     ·                 │     ·              │     ·                  │          ·          │      ·             │   ·        │   ·     │           ·  │          ·               │  ·                │                                         ·                                          │                                ·                                          │  ·                                   │            ·            │                ·    │                        ·    │
│       ·   │  ·         │   ·          │     ·               │          ·  │               · │     ·               │     ·                 │     ·              │     ·                  │          ·          │      ·             │   ·        │   ·     │           ·  │          ·               │  ·                │                                         ·                                          │                                ·                                          │  ·                                   │            ·            │                ·    │                        ·    │
│       ·   │  ·         │   ·          │     ·               │          ·  │               · │     ·               │     ·                 │     ·              │     ·                  │          ·          │      ·             │   ·        │   ·     │           ·  │          ·               │  ·                │                                         ·                                          │                                ·                                          │  ·                                   │            ·            │                ·    │                        ·    │
│    534033 │ Alexis     │ Mac Allister │ Alexis Mac Allister │        2025 │              31 │ alexis-mac-allister │ Argentina             │ Santa Rosa         │ Argentina              │ 1998-12-24 00:00:00 │ Central Midfield   │ Midfield   │ right   │          176 │ 2028-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/534033-1669835342.jpg?lm=1  │ https://www.transfermarkt.co.uk/alexis-mac-allister/profil/spieler/534033 │ GB1                                  │ Liverpool Football Club │            85000000 │                    85000000 │
│    598577 │ Florian    │ Wirtz        │ Florian Wirtz       │        2025 │              31 │ florian-wirtz       │ Germany               │ Pulheim            │ Germany                │ 2003-05-03 00:00:00 │ Attacking Midfield │ Midfield   │ right   │          177 │ 2030-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/598577-1689710503.jpg?lm=1  │ https://www.transfermarkt.co.uk/florian-wirtz/profil/spieler/598577       │ GB1                                  │ Liverpool Football Club │           110000000 │                   140000000 │
│    624258 │ Conor      │ Bradley      │ Conor Bradley       │        2025 │              31 │ conor-bradley       │ Northern Ireland      │ Castlederg         │ Northern Ireland       │ 2003-07-09 00:00:00 │ Right-Back         │ Defender   │ right   │          181 │ 2029-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/624258-1762340233.jpg?lm=1  │ https://www.transfermarkt.co.uk/conor-bradley/profil/spieler/624258       │ GB1                                  │ Liverpool Football Club │            30000000 │                    30000000 │
│    633652 │ Calvin     │ Ramsay       │ Calvin Ramsay       │        2025 │              31 │ calvin-ramsay       │ Scotland              │ Aberdeen           │ Scotland               │ 2003-07-31 00:00:00 │ Right-Back         │ Defender   │ right   │          177 │ 2027-06-30 00:00:00      │ PLG               │ https://img.a.transfermarkt.technology/portrait/header/633652-1628698224.jpg?lm=1  │ https://www.transfermarkt.co.uk/calvin-ramsay/profil/spieler/633652       │ GB1                                  │ Liverpool Football Club │             5000000 │                     5000000 │
│    709726 │ Hugo       │ Ekitiké      │ Hugo Ekitiké        │        2025 │              31 │ hugo-ekitike        │ France                │ Reims              │ France                 │ 2002-06-20 00:00:00 │ Centre-Forward     │ Attack     │ right   │          190 │ 2031-06-30 00:00:00      │ OSA               │ https://img.a.transfermarkt.technology/portrait/header/709726-1758714741.jpg?lm=1  │ https://www.transfermarkt.co.uk/hugo-ekitike/profil/spieler/709726        │ GB1                                  │ Liverpool Football Club │            85000000 │                    85000000 │
│    730861 │ Milos      │ Kerkez       │ Milos Kerkez        │        2025 │              31 │ milos-kerkez        │ Serbia and Montenegro │ Vrbas              │ Hungary                │ 2003-11-07 00:00:00 │ Left-Back          │ Defender   │ left    │          180 │ 2030-06-30 00:00:00      │ LIAN Sports Group │ https://img.a.transfermarkt.technology/portrait/header/730861-1660762995.jpg?lm=1  │ https://www.transfermarkt.co.uk/milos-kerkez/profil/spieler/730861        │ GB1                                  │ Liverpool Football Club │            40000000 │                    40000000 │
│    864799 │ Stefan     │ Bajcetic     │ Stefan Bajcetic     │        2025 │              31 │ stefan-bajcetic     │ Spain                 │ Vigo               │ Spain                  │ 2004-10-22 00:00:00 │ Defensive Midfield │ Midfield   │ right   │          185 │ 2027-06-30 00:00:00      │ ROOF              │ https://img.a.transfermarkt.technology/portrait/header/864799-1661441233.jpg?lm=1  │ https://www.transfermarkt.co.uk/stefan-bajcetic/profil/spieler/864799     │ GB1                                  │ Liverpool Football Club │             7000000 │                     9000000 │
│   1045123 │ Trey       │ Nyoni        │ Trey Nyoni          │        2025 │              31 │ trey-nyoni          │ England               │ Leicester          │ England                │ 2007-06-30 00:00:00 │ Central Midfield   │ Midfield   │ right   │          180 │ 2026-06-30 00:00:00      │ SEG               │ https://img.a.transfermarkt.technology/portrait/header/1045123-1708933240.jpg?lm=1 │ https://www.transfermarkt.co.uk/trey-nyoni/profil/spieler/1045123         │ GB1                                  │ Liverpool Football Club │             6000000 │                     6000000 │
│   1086619 │ Giovanni   │ Leoni        │ Giovanni Leoni      │        2025 │              31 │ giovanni-leoni      │ Italy                 │ Roma               │ Italy                  │ 2006-12-21 00:00:00 │ Centre-Back        │ Defender   │ right   │          196 │ 2031-06-30 00:00:00      │ Excellence Sport  │ https://img.a.transfermarkt.technology/portrait/header/1086619-1751532399.jpg?lm=1 │ https://www.transfermarkt.co.uk/giovanni-leoni/profil/spieler/1086619     │ GB1                                  │ Liverpool Football Club │            25000000 │                    25000000 │
│   1108466 │ Rio        │ Ngumoha      │ Rio Ngumoha         │        2025 │              31 │ rio-ngumoha         │ England               │ London             │ England                │ 2008-08-29 00:00:00 │ Left Winger        │ Attack     │ right   │          170 │ 2028-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/1108466-1730834754.jpg?lm=1 │ https://www.transfermarkt.co.uk/rio-ngumoha/profil/spieler/1108466        │ GB1                                  │ Liverpool Football Club │            15000000 │                    15000000 │
├───────────┴────────────┴──────────────┴─────────────────────┴─────────────┴─────────────────┴─────────────────────┴───────────────────────┴────────────────────┴────────────────────────┴─────────────────────┴────────────────────┴────────────┴─────────┴──────────────┴──────────────────────────┴───────────────────┴────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────────────────────┴─────────────────────┴─────────────────────────────┤
│ 24 rows (20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 23 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
# Example: liverpool current player valuations over time

q = """
SELECT P.player_id, P.name, V.date, V.market_value_in_eur
FROM read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/players.csv.gz') P
JOIN read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/player_valuations.csv.gz') V ON P.player_id = V.player_id
WHERE current_club_domestic_competition_id = 'GB1' AND last_season = 2025
AND P.current_club_id = 31
ORDER BY P.player_id, V.date
"""

duckdb.sql(q).show() # Run the query

┌───────────┬─────────────────┬────────────┬─────────────────────┐
│ player_id │      name       │    date    │ market_value_in_eur │
│   int64   │     varchar     │    date    │        int64        │
├───────────┼─────────────────┼────────────┼─────────────────────┤
│    105470 │ Alisson         │ 2012-05-12 │              150000 │
│    105470 │ Alisson         │ 2012-08-02 │              150000 │
│    105470 │ Alisson         │ 2014-07-08 │              300000 │
│    105470 │ Alisson         │ 2015-01-02 │             1000000 │
│    105470 │ Alisson         │ 2015-11-09 │             3500000 │
│    105470 │ Alisson         │ 2017-02-01 │             7000000 │
│    105470 │ Alisson         │ 2017-08-06 │             7000000 │
│    105470 │ Alisson         │ 2018-07-06 │            60000000 │
│    105470 │ Alisson         │ 2019-10-12 │            90000000 │
│    105470 │ Alisson         │ 2020-08-04 │            72000000 │
│       ·   │    ·            │     ·      │                ·    │
│       ·   │    ·            │     ·      │                ·    │
│       ·   │    ·            │     ·      │                ·    │
│    730861 │ Milos Kerkez    │ 2023-09-10 │            18000000 │
│    730861 │ Milos Kerkez    │ 2025-09-12 │            40000000 │
│    864799 │ Stefan Bajcetic │ 2022-03-11 │             1000000 │
│    864799 │ Stefan Bajcetic │ 2025-09-06 │             9000000 │
│    864799 │ Stefan Bajcetic │ 2025-09-12 │             7000000 │
│   1045123 │ Trey Nyoni      │ 2025-09-12 │             6000000 │
│   1086619 │ Giovanni Leoni  │ 2023-01-07 │              100000 │
│   1086619 │ Giovanni Leoni  │ 2024-03-06 │             4500000 │
│   1086619 │ Giovanni Leoni  │ 2025-09-12 │            25000000 │
│   1108466 │ Rio Ngumoha     │ 2025-09-12 │            15000000 │
├───────────┴─────────────────┴────────────┴─────────────────────┤
│ 195 rows (20 shown)                                  4 columns │
└────────────────────────────────────────────────────────────────┘

In [5]:
# Example: Basic Performance Stats

q = """
SELECT *
FROM read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/appearances.csv.gz') A
LIMIT 10
"""

duckdb.sql(q).show()

┌────────────────┬─────────┬───────────┬────────────────┬────────────────────────┬────────────┬──────────────────┬────────────────┬──────────────┬───────────┬───────┬─────────┬────────────────┐
│ appearance_id  │ game_id │ player_id │ player_club_id │ player_current_club_id │    date    │   player_name    │ competition_id │ yellow_cards │ red_cards │ goals │ assists │ minutes_played │
│    varchar     │  int64  │   int64   │     int64      │         int64          │    date    │     varchar      │    varchar     │    int64     │   int64   │ int64 │  int64  │     int64      │
├────────────────┼─────────┼───────────┼────────────────┼────────────────────────┼────────────┼──────────────────┼────────────────┼──────────────┼───────────┼───────┼─────────┼────────────────┤
│ 2231978_38004  │ 2231978 │     38004 │            853 │                    235 │ 2012-07-03 │ Aurélien Joachim │ CLQ            │            0 │         0 │     2 │       0 │             90 │
│ 2233748_79232  │ 2233748 │     79232 │           8841 │                   2698 │ 2012-07-05 │ Ruslan Abyshov   │ ELQ            │            0 │         0 │     0 │       0 │             90 │
│ 2234413_42792  │ 2234413 │     42792 │           6251 │                    465 │ 2012-07-05 │ Sander Puri      │ ELQ            │            0 │         0 │     0 │       0 │             45 │
│ 2234418_73333  │ 2234418 │     73333 │           1274 │                   6646 │ 2012-07-05 │ Vegar Hedenstad  │ ELQ            │            0 │         0 │     0 │       0 │             90 │
│ 2234421_122011 │ 2234421 │    122011 │            195 │                   3008 │ 2012-07-05 │ Markus Henriksen │ ELQ            │            0 │         0 │     0 │       1 │             90 │
│ 2234421_146889 │ 2234421 │    146889 │            195 │                   2778 │ 2012-07-05 │ Peter Ankersen   │ ELQ            │            1 │         0 │     0 │       0 │             90 │
│ 2235539_28716  │ 2235539 │     28716 │            282 │                   7185 │ 2012-07-05 │ Adi Adilovic     │ ELQ            │            0 │         0 │     0 │       0 │             90 │
│ 2235539_69445  │ 2235539 │     69445 │            282 │                  19771 │ 2012-07-05 │ Ivan Sesar       │ ELQ            │            1 │         0 │     0 │       1 │             90 │
│ 2235545_19409  │ 2235545 │     19409 │            317 │                    200 │ 2012-07-05 │ Willem Janssen   │ ELQ            │            0 │         0 │     0 │       0 │             45 │
│ 2235545_30003  │ 2235545 │     30003 │            317 │                    317 │ 2012-07-05 │ Wout Brama       │ ELQ            │            0 │         0 │     0 │       0 │             90 │
├────────────────┴─────────┴───────────┴────────────────┴────────────────────────┴────────────┴──────────────────┴────────────────┴──────────────┴───────────┴───────┴─────────┴────────────────┤
│ 10 rows                                                                                                                                                                            13 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## Understat API

In [2]:
# Create connection
understat = UnderstatClient()

In [3]:
# Get all player data for a league/season
epl_players = understat.league(league="EPL").get_player_data(season="2025")

# Make into a dataframe
player_df = pd.DataFrame(epl_players)

player_df.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,8260,Erling Haaland,29,2439,22,23.13693391531706,7,4.766327390447259,102,21,1,0,F S,Manchester City,19,20.092258475720882,26.238575093448162,4.129314249381423
1,13222,Thiago,31,2662,19,21.101609505712986,1,3.155416488647461,71,19,6,0,F S,Brentford,13,15.773427560925484,19.4751720353961,3.4934082627296448
2,11363,Antoine Semenyo,29,2597,15,11.201724836602807,4,3.091043023392558,68,32,6,0,F M,"Bournemouth,Manchester City",14,9.67938713915646,16.244873739778996,4.950852746143937
3,8272,João Pedro,31,2345,14,14.15835139900446,5,3.9609613977372646,63,28,4,0,F M S,Chelsea,14,14.15835139900446,17.67835896089673,4.659978250041604
4,501,Danny Welbeck,30,1832,12,10.899193301796913,0,1.8765279427170753,43,18,5,0,F S,Brighton,11,8.6156866569072,12.241745796054602,3.454270198009908

In [4]:
player_df.sort_values(by="time", ascending=False).head(20)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
218,9558,Hannibal Mejbri,23,996,1,0.4494898612610996,3,1.9867054745554924,14,14,7,0,M S,Burnley,1,0.4494898612610996,4.205114980228245,2.764857292175293
459,12910,Mads Hermansen,11,990,0,0,0,0,0,0,0,0,GK,West Ham,0,0,1.1277148462831974,1.1277148462831974
56,5304,Mikel Merino,21,977,4,4.551519326865673,3,2.2901399955153465,21,12,1,0,F M S,Arsenal,4,4.551519326865673,7.0440468192100525,3.1536439023911953
435,11808,Andrey Santos,23,977,0,1.7154290862381458,0,0.6522208489477634,8,7,4,0,M S,Chelsea,0,1.7154290862381458,5.09560789167881,3.811923023313284
229,10770,Soungoutou Magassa,20,972,1,0.6193040320649743,0,0.7463846588507295,7,5,4,0,M S,West Ham,1,0.6193040320649743,2.4097342267632484,1.522645689547062
466,13150,Jack Fletcher,3,97,0,0.037386249750852585,0,0.11487564817070961,1,2,0,0,S,Manchester United,0,0.037386249750852585,0.26276974007487297,0.14789408445358276
217,9501,Fabio Carvalho,6,97,1,0.6895682029426098,0,0,2,0,0,0,M S,Brentford,1,0.6895682029426098,0.6895682029426098,0
203,8252,Nicolás Domínguez,20,965,1,0.7576484093442559,0,0.7514081094413996,16,9,1,0,M S,Nottingham Forest,1,0.7576484093442559,3.407697480171919,2.2724769935011864
298,5355,Jacob Bruun Larsen,23,965,0,1.3876315392553806,1,1.2826955989003181,16,11,0,0,F M S,Burnley,0,1.3876315392553806,4.335738031193614,2.199708631262183
393,10120,Conor Bradley,15,962,0,0.21982916723936796,1,1.1937107481062412,6,4,5,0,D S,Liverpool,0,0.21982916723936796,3.412436105310917,2.4054819140583277
471,13247,Ezra Mayers,6,96,0,0.10989412665367126,0,0.11634047329425812,1,2,0,0,S,West Ham,0,0.10989412665367126,0.39119094237685204,0.16495634242892265
325,6756,Dwight McNeil,18,956,0,1.1852928027510643,1,1.1757264733314514,17,12,1,0,F M S,Everton,0,1.1852928027510643,3.7617278918623924,2.0566610246896744
278,1024,Tyrone Mings,13,954,0,0.9410608746111393,0,0.7093149498105049,7,5,0,0,D S,Aston Villa,0,0.9410608746111393,2.3480710349977016,2.036162167787552
355,8489,Jorge Cuenca,14,948,0,0.050821494311094284,0,0.5158752724528313,1,3,5,0,D S,Fulham,0,0.050821494311094284,2.2441382743418217,2.2441382743418217
411,10822,Wilson Odobert,24,946,0,2.460178238339722,2,1.9524234533309937,21,20,0,0,F M S,Tottenham,0,2.460178238339722,5.9682222586125135,2.8834201879799366
191,7078,Sean Longstaff,17,944,1,0.6963180564343929,2,2.4830981642007828,13,22,2,0,M S,Leeds,1,0.6963180564343929,2.797569300979376,1.7294726222753525
347,7943,Igor Julio,4,94,0,0,0,0.018099337816238403,0,1,0,0,D S,West Ham,0,0,0.06989672780036926,0.06989672780036926
169,934,Axel Tuanzebe,11,939,1,0.5582677125930786,0,0,2,0,1,0,D,Burnley,1,0.5582677125930786,2.4150575436651707,1.856789831072092
167,885,Kyle Walker-Peters,18,937,1,1.1882447563111782,0,0.22901761904358864,5,5,2,0,D S,West Ham,1,1.1882447563111782,3.0865802317857742,1.9071616008877754
463,13068,Morato,15,935,0,1.401793820783496,0,0.013815321959555149,4,1,4,0,D S,Nottingham Forest,0,1.401793820783496,2.6422858498990536,2.0910839401185513

In [38]:
player_df[player_df["player_name"] == "Antoine Semenyo"]

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
2,11363,Antoine Semenyo,29,2597,15,11.201724836602807,4,3.091043023392558,68,32,6,0,F M,"Bournemouth,Manchester City",14,9.67938713915646,16.244873739778996,4.950852746143937

In [5]:
# Look at all positions

player_df["position"].unique()

array(['F S', 'F M', 'F M S', 'M S', 'M', 'D M', 'D M S', 'D S', 'D',
       'D F M S', 'F', 'S', 'GK', 'GK S'], dtype=object)

In [29]:
# Get all match stats for a particular player - Erling Haaland
player_matches = understat.player(player='8260').get_match_data()

# Convert to dataframe
player_matches_df = pd.DataFrame(player_matches)

# Sort by date
player_matches_df = player_matches_df.sort_values(by="date")

player_matches_df.head()

,goals,shots,xG,time,position,h_team,a_team,h_goals,a_goals,date,id,season,roster_id,xA,assists,key_passes,npg,npxG,xGChain,xGBuildup
192,3,3,1.3227900266647339,33,Sub,Augsburg,Borussia Dortmund,3,5,2020-01-18,12562,2019,389276,0,0,0,3,1.3227900266647339,1.3459999561309814,0.023214099928736687
191,2,3,1.3333300352096558,23,Sub,Borussia Dortmund,FC Cologne,5,1,2020-01-24,12566,2019,389900,0,0,0,2,1.3333300352096558,1.3333300352096558,0
190,2,2,0.7829639911651611,77,FW,Borussia Dortmund,Union Berlin,5,0,2020-02-01,12574,2019,391067,0.06835760176181793,0,1,2,0.7829639911651611,0.7862169742584229,0.5620520114898682
189,0,2,0.10662200301885605,90,FW,Bayer Leverkusen,Borussia Dortmund,4,3,2020-02-08,12584,2019,392772,0,0,0,0,0.10662200301885605,0.422342985868454,0.3633730113506317
188,1,2,0.6940990090370178,80,FW,Borussia Dortmund,Eintracht Frankfurt,4,0,2020-02-14,12592,2019,393399,0.04634920135140419,0,1,1,0.6940990090370178,0.7866899967193604,0.046242501586675644

In [ ]:
team_season_leagues = pd.read_csv("../data/team_season_leagues.csv")

pd.merge(player_matches_df, team_season_leagues)

In [39]:
understat.player(player='11363').get_season_data()['season']

[{'position': 'MR',
  'games': '20',
  'goals': '10',
  'shots': '49',
  'time': '1800',
  'xG': '7.9325351398438215',
  'assists': '3',
  'xA': '2.4660277236253023',
  'key_passes': '25',
  'season': '2025',
  'team': 'Bournemouth',
  'yellow': '6',
  'red': '0',
  'npg': '9',
  'npxG': '6.410197442397475',
  'xGChain': '10.571022145450115',
  'xGBuildup': '3.088812258094549'},
 {'position': 'MR',
  'games': '9',
  'goals': '5',
  'shots': '19',
  'time': '797',
  'xG': '3.2691896967589855',
  'assists': '1',
  'xA': '0.6250152997672558',
  'key_passes': '7',
  'season': '2025',
  'team': 'Manchester City',
  'yellow': '0',
  'red': '0',
  'npg': '5',
  'npxG': '3.2691896967589855',
  'xGChain': '5.67385159432888',
  'xGBuildup': '1.862040488049388'},
 {'position': 'FW',
  'games': '37',
  'goals': '11',
  'shots': '126',
  'time': '3219',
  'xG': '14.549346312880516',
  'assists': '5',
  'xA': '6.608794005587697',
  'key_passes': '46',
  'season': '2024',
  'team': 'Bournemouth',
  'yellow': '9',
  'red': '0',
  'npg': '11',
  'npxG': '14.549346312880516',
  'xGChain': '26.17976476252079',
  'xGBuildup': '7.88416787609458'},
 {'position': 'Sub',
  'games': '33',
  'goals': '8',
  'shots': '70',
  'time': '2141',
  'xG': '6.423830641433597',
  'assists': '2',
  'xA': '3.799709178507328',
  'key_passes': '29',
  'season': '2023',
  'team': 'Bournemouth',
  'yellow': '7',
  'red': '0',
  'npg': '8',
  'npxG': '6.423830641433597',
  'xGChain': '15.41077795997262',
  'xGBuildup': '5.7127093356102705'},
 {'position': 'FW',
  'games': '11',
  'goals': '1',
  'shots': '3',
  'time': '237',
  'xG': '0.3684318736195564',
  'assists': '0',
  'xA': '0.07599039375782013',
  'key_passes': '2',
  'season': '2022',
  'team': 'Bournemouth',
  'yellow': '0',
  'red': '0',
  'npg': '1',
  'npxG': '0.3684318736195564',
  'xGChain': '1.224020279943943',
  'xGBuildup': '0.7795986160635948'}]

In [12]:
# Get all player names and ids and save to csv for later use

leagues = ["EPL", "La_Liga", "Bundesliga", "Serie_A", "Ligue_1"]
seasons = list(range(2015, 2026))

id_to_name = {}
for league in leagues:
    for season in seasons:
        players = understat.league(league=league).get_player_data(season=str(season))
        for p in players:
            id_to_name[p["id"]] = p["player_name"]
            
id_names = pd.DataFrame({"player_id":id_to_name.keys(), "name":id_to_name.values()})
id_names.to_csv("../data/id_names.csv")

In [28]:
# Get mapping from team/season to league
team_season_to_league = {}
for league in leagues:
    for season in seasons:
        teams = understat.league(league=league).get_team_data(season=str(season))
        for team in teams:
            team_season_to_league[(teams[team]['title'], season)] = league

# Save as df
team_season_leagues = pd.DataFrame({"team":[k[0] for k in team_season_to_league.keys()],
                                   "season":[k[1] for k in team_season_to_league.keys()],
                                   "league":[v for v in team_season_to_league.values()]})

team_season_leagues.to_csv("../data/team_season_leagues.csv")

In [42]:
understat.league(league="EPL").get_match_data(season="2025")

[{'id': '28778',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '4', 'a': '2'},
  'xG': {'h': '2.33007', 'a': '1.57303'},
  'datetime': '2025-08-15 19:00:00',
  'forecast': {'w': '0.5498', 'd': '0.2276', 'l': '0.2226'}},
 {'id': '28779',
  'isResult': True,
  'h': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'a': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '0.318601', 'a': '1.40098'},
  'datetime': '2025-08-16 11:30:00',
  'forecast': {'w': '0.0629', 'd': '0.2371', 'l': '0.7'}},
 {'id': '28780',
  'isResult': True,
  'h': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.44008', 'a': '0.902883'},
  'datetime': '2025-08-16 14:00:00',
  'forecast': {'w': '0.5158', 'd': '0.3088', 'l': '0.1754'}},
 {'id': '28781',
  'isResult': True,
  'h': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '0.724368', 'a': '0.558948'},
  'datetime': '2025-08-16 14:00:00',
  'forecast': {'w': '0.363', 'd': '0.391', 'l': '0.246'}},
 {'id': '28782',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '1.97858', 'a': '0.734138'},
  'datetime': '2025-08-16 14:00:00',
  'forecast': {'w': '0.7032', 'd': '0.1993', 'l': '0.0975'}},
 {'id': '28783',
  'isResult': True,
  'h': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '0', 'a': '4'},
  'xG': {'h': '0.519436', 'a': '2.29903'},
  'datetime': '2025-08-16 16:30:00',
  'forecast': {'w': '0.0404', 'd': '0.1179', 'l': '0.8417'}},
 {'id': '28784',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '1.36793', 'a': '1.03414'},
  'datetime': '2025-08-17 13:00:00',
  'forecast': {'w': '0.4404', 'd': '0.2929', 'l': '0.2667'}},
 {'id': '28785',
  'isResult': True,
  'h': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'a': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '1.7555', 'a': '1.32516'},
  'datetime': '2025-08-17 13:00:00',
  'forecast': {'w': '0.4714', 'd': '0.2855', 'l': '0.2431'}},
 {'id': '28786',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '1.37653', 'a': '1.3304'},
  'datetime': '2025-08-17 15:30:00',
  'forecast': {'w': '0.3408', 'd': '0.3074', 'l': '0.3518'}},
 {'id': '28787',
  'isResult': True,
  'h': {'id': '245', 'title': 'Leeds', 'short_title': 'LED'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '2.3812', 'a': '0.674338'},
  'datetime': '2025-08-18 19:00:00',
  'forecast': {'w': '0.8116', 'd': '0.1394', 'l': '0.049'}},
 {'id': '28788',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '1', 'a': '5'},
  'xG': {'h': '0.978572', 'a': '3.94997'},
  'datetime': '2025-08-22 19:00:00',
  'forecast': {'w': '0.0153', 'd': '0.0485', 'l': '0.9362'}},
 {'id': '28789',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '0', 'a': '2'},
  'xG': {'h': '1.2475', 'a': '1.28015'},
  'datetime': '2025-08-23 11:30:00',
  'forecast': {'w': '0.3526', 'd': '0.2889', 'l': '0.3585'}},
 {'id': '28790',
  'isResult': True,
  'h': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'a': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '1.12964', 'a': '0.976852'},
  'datetime': '2025-08-23 14:00:00',
  'forecast': {'w': '0.4019', 'd': '0.3328', 'l': '0.2653'}},
 {'id': '28791',
  'isResult': True,
  'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'a': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '1.00381', 'a': '1.12127'},
  'datetime': '2025-08-23 14:00:00',
  'forecast': {'w': '0.2978', 'd': '0.3293', 'l': '0.3729'}},
 {'id': '28792',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '1.78462', 'a': '0.373367'},
  'datetime': '2025-08-23 14:00:00',
  'forecast': {'w': '0.7888', 'd': '0.1642', 'l': '0.047'}},
 {'id': '28793',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '245', 'title': 'Leeds', 'short_title': 'LED'},
  'goals': {'h': '5', 'a': '0'},
  'xG': {'h': '2.73761', 'a': '0.156761'},
  'datetime': '2025-08-23 16:30:00',
  'forecast': {'w': '0.9569', 'd': '0.039', 'l': '0.0041'}},
 {'id': '28794',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.10188', 'a': '1.32987'},
  'datetime': '2025-08-24 13:00:00',
  'forecast': {'w': '0.2822', 'd': '0.3071', 'l': '0.4107'}},
 {'id': '28795',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '1.80116', 'a': '2.08487'},
  'datetime': '2025-08-24 13:00:00',
  'forecast': {'w': '0.2765', 'd': '0.2775', 'l': '0.446'}},
 {'id': '28796',
  'isResult': True,
  'h': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.65333', 'a': '1.54603'},
  'datetime': '2025-08-24 15:30:00',
  'forecast': {'w': '0.3868', 'd': '0.2852', 'l': '0.328'}},
 {'id': '28797',
  'isResult': True,
  'h': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '2', 'a': '3'},
  'xG': {'h': '1.96342', 'a': '0.646559'},
  'datetime': '2025-08-25 19:00:00',
  'forecast': {'w': '0.7493', 'd': '0.1793', 'l': '0.0714'}},
 {'id': '28798',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '2.4324', 'a': '0.736228'},
  'datetime': '2025-08-30 11:30:00',
  'forecast': {'w': '0.811', 'd': '0.1338', 'l': '0.0552'}},
 {'id': '28799',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.17067', 'a': '2.1201'},
  'datetime': '2025-08-30 14:00:00',
  'forecast': {'w': '0.016', 'd': '0.1089', 'l': '0.8751'}},
 {'id': '28800',
  'isResult': True,
  'h': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '2', 'a': '3'},
  'xG': {'h': '0.943257', 'a': '2.03791'},
  'datetime': '2025-08-30 14:00:00',
  'forecast': {'w': '0.1205', 'd': '0.2084', 'l': '0.6711'}},
 {'id': '28801',
  'isResult': True,
  'h': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'a': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.57127', 'a': '1.44604'},
  'datetime': '2025-08-30 14:00:00',
  'forecast': {'w': '0.3654', 'd': '0.3194', 'l': '0.3152'}},
 {'id': '28802',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'goals': {'h': '3', 'a': '2'},
  'xG': {'h': '4.02237', 'a': '1.32618'},
  'datetime': '2025-08-30 14:00:00',
  'forecast': {'w': '0.911', 'd': '0.0655', 'l': '0.0235'}},
 {'id': '28803',
  'isResult': True,
  'h': {'id': '245', 'title': 'Leeds', 'short_title': 'LED'},
  'a': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '0.6773', 'a': '0.303635'},
  'datetime': '2025-08-30 16:30:00',
  'forecast': {'w': '0.408', 'd': '0.4518', 'l': '0.1402'}},
 {'id': '28804',
  'isResult': True,
  'h': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '0.716018', 'a': '2.236'},
  'datetime': '2025-08-31 13:00:00',
  'forecast': {'w': '0.0594', 'd': '0.1552', 'l': '0.7854'}},
 {'id': '28805',
  'isResult': True,
  'h': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '2.20864', 'a': '2.13418'},
  'datetime': '2025-08-31 13:00:00',
  'forecast': {'w': '0.3828', 'd': '0.2726', 'l': '0.3446'}},
 {'id': '28806',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '0.481404', 'a': '0.485679'},
  'datetime': '2025-08-31 15:30:00',
  'forecast': {'w': '0.2681', 'd': '0.4624', 'l': '0.2695'}},
 {'id': '28807',
  'isResult': True,
  'h': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '1.20586', 'a': '2.59713'},
  'datetime': '2025-08-31 18:00:00',
  'forecast': {'w': '0.0734', 'd': '0.161', 'l': '0.7656'}},
 {'id': '28808',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '2.8817', 'a': '0.293681'},
  'datetime': '2025-09-13 11:30:00',
  'forecast': {'w': '0.9419', 'd': '0.048', 'l': '0.0101'}},
 {'id': '28809',
  'isResult': True,
  'h': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'a': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '1.19186', 'a': '0.375942'},
  'datetime': '2025-09-13 14:00:00',
  'forecast': {'w': '0.6234', 'd': '0.2851', 'l': '0.0915'}},
 {'id': '28810',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.44187', 'a': '0.624923'},
  'datetime': '2025-09-13 14:00:00',
  'forecast': {'w': '0.6177', 'd': '0.2664', 'l': '0.1159'}},
 {'id': '28811',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '1.75805', 'a': '0.354129'},
  'datetime': '2025-09-13 14:00:00',
  'forecast': {'w': '0.7823', 'd': '0.1686', 'l': '0.0491'}},
 {'id': '28812',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '1.8927', 'a': '0.354327'},
  'datetime': '2025-09-13 14:00:00',
  'forecast': {'w': '0.7847', 'd': '0.1658', 'l': '0.0495'}},
 {'id': '28813',
  'isResult': True,
  'h': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'a': {'id': '245', 'title': 'Leeds', 'short_title': 'LED'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '1.13979', 'a': '0.830398'},
  'datetime': '2025-09-13 14:00:00',
  'forecast': {'w': '0.4371', 'd': '0.3383', 'l': '0.2246'}},
 {'id': '28814',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '0.793248', 'a': '1.51402'},
  'datetime': '2025-09-13 16:30:00',
  'forecast': {'w': '0.1696', 'd': '0.2807', 'l': '0.5497'}},
 {'id': '28815',
  'isResult': True,
  'h': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '1.17533', 'a': '0.755999'},
  'datetime': '2025-09-13 19:00:00',
  'forecast': {'w': '0.495', 'd': '0.2994', 'l': '0.2056'}},
 {'id': '28816',
  'isResult': True,
  'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.168041', 'a': '2.79492'},
  'datetime': '2025-09-14 13:00:00',
  'forecast': {'w': '0.0037', 'd': '0.0387', 'l': '0.9576'}},
 {'id': '28817',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '1.99725', 'a': '1.51915'},
  'datetime': '2025-09-14 15:30:00',
  'forecast': {'w': '0.4799', 'd': '0.2573', 'l': '0.2628'}},
 {'id': '28818',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.06166', 'a': '0.721371'},
  'datetime': '2025-09-20 11:30:00',
  'forecast': {'w': '0.4455', 'd': '0.33', 'l': '0.2245'}},
 {'id': '28819',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '0.466365', 'a': '2.33565'},
  'datetime': '2025-09-20 14:00:00',
  'forecast': {'w': '0.035', 'd': '0.1161', 'l': '0.8489'}},
 {'id': '28820',
  'isResult': True,
  'h': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'a': {'id': '245', 'title': 'Leeds', 'short_title': 'LED'},
  'goals': {'h': '1', 'a': '3'},
  'xG': {'h': '1.5661', 'a': '0.456988'},
  'datetime': '2025-09-20 14:00:00',
  'forecast': {'w': '0.6878', 'd': '0.2266', 'l': '0.0856'}},
 {'id': '28821',
  'isResult': True,
  'h': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '1.40466', 'a': '1.19181'},
  'datetime': '2025-09-20 14:00:00',
  'forecast': {'w': '0.4028', 'd': '0.3289', 'l': '0.2683'}},
 {'id': '28822',
  'isResult': True,
  'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.14159', 'a': '0.830779'},
  'datetime': '2025-09-20 14:00:00',
  'forecast': {'w': '0.4397', 'd': '0.3168', 'l': '0.2435'}},
 {'id': '28824',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.34458', 'a': '0.469843'},
  'datetime': '2025-09-20 16:30:00',
  'forecast': {'w': '0.6294', 'd': '0.2748', 'l': '0.0958'}},
 {'id': '28825',
  'isResult': True,
  'h': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'a': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '1.52431', 'a': '0.826556'},
  'datetime': '2025-09-20 19:00:00',
  'forecast': {'w': '0.5643', 'd': '0.2588', 'l': '0.1769'}},
 {'id': '28823',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '0.55066', 'a': '0.153629'},
  'datetime': '2025-09-21 13:00:00',
  'forecast': {'w': '0.3942', 'd': '0.5216', 'l': '0.0842'}},
 {'id': '28826',
  'isResult': True,
  'h': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'a': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.938312', 'a': '0.939354'},
  'datetime': '2025-09-21 13:00:00',
  'forecast': {'w': '0.3258', 'd': '0.3463', 'l': '0.3279'}},
 {'id': '28827',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.718575', 'a': '1.1227'},
  'datetime': '2025-09-21 15:30:00',
  'forecast': {'w': '0.2028', 'd': '0.3221', 'l': '0.4751'}},
 {'id': '28828',
  'isResult': True,
  'h': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '2.78726', 'a': '2.23609'},
  'datetime': '2025-09-27 11:30:00',
  'forecast': {'w': '0.5118', 'd': '0.2491', 'l': '0.2391'}},
 {'id': '28829',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'goals': {'h': '1', 'a': '3'},
  'xG': {'h': '2.02653', 'a': '2.4751'},
  'datetime': '2025-09-27 14:00:00',
  'forecast': {'w': '0.2603', 'd': '0.2482', 'l': '0.4915'}},
 {'id': '28830',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '3.53323', 'a': '3.10176'},
  'datetime': '2025-09-27 14:00:00',
  'forecast': {'w': '0.4872', 'd': '0.1968', 'l': '0.316'}},
 {'id': '28832',
  'isResult': True,
  'h': {'id': '245', 'title': 'Leeds', 'short_title': 'LED'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '2.04728', 'a': '1.06033'},
  'datetime': '2025-09-27 14:00:00',
  'forecast': {'w': '0.6258', 'd': '0.219', 'l': '0.1552'}},
 {'id': '28833',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'goals': {'h': '5', 'a': '1'},
  'xG': {'h': '3.22133', 'a': '0.509491'},
  'datetime': '2025-09-27 14:00:00',
  'forecast': {'w': '0.9279', 'd': '0.0602', 'l': '0.0119'}},
 {'id': '28834',
  'isResult': True,
  'h': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'a': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '1.4203', 'a': '1.94154'},
  'datetime': '2025-09-27 16:30:00',
  'forecast': {'w': '0.2527', 'd': '0.2346', 'l': '0.5127'}},
 {'id': '28835',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.818711', 'a': '1.15951'},
  'datetime': '2025-09-27 19:00:00',
  'forecast': {'w': '0.2181', 'd': '0.3376', 'l': '0.4443'}},
 {'id': '28831',
  'isResult': True,
  'h': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '1.36575', 'a': '0.952612'},
  'datetime': '2025-09-28 13:00:00',

In [57]:
from collections import defaultdict

player_info_map = defaultdict(list)

# Get all matches in this league/season
matches = understat.league(league=league).get_match_data(season=str(season))
        
for match in matches:
    match_id = match['id']
    # Get player stats for this specific match
    roster = understat.match(match=match_id).get_roster_data()
            
    for _, player_info in roster['h'].items():  # home team
        player_info_map[player_info['player_id']].append(player_info)
                
    for _, player_info in roster['a'].items():  # away team
        player_info_map[player_info['player_id']].append(player_info)

In [2]:
understat.match(match='30520').get_roster_data()

NameError: name 'understat' is not defined

In [7]:
understat.league(league="EPL").get_match_data(season="2025")[0]['datetime'][:10]

'2025-08-15'

In [19]:
understat.match(match='30467').get_roster_data()

InvalidMatch: 30467 is not a valid match

In [60]:
pd.DataFrame(player_info_map['560'])

,id,goals,own_goals,shots,xG,time,player_id,team_id,position,player,...,yellow_card,red_card,roster_in,roster_out,key_passes,assists,xA,xGChain,xGBuildup,positionOrder
0,620382,0,0,0,0,90,560,89,GK,Sergio Romero,...,0,0,0,0,0,0,0,0,0,1
1,57370,0,0,0,0,90,560,89,GK,Sergio Romero,...,0,0,0,0,0,0,0,0.0589383989572525,0.0589383989572525,1
2,62806,0,0,0,0,90,560,89,GK,Sergio Romero,...,0,0,0,0,0,0,0,0.014860300347208977,0.014860300347208977,1
3,63779,0,0,0,0,90,560,89,GK,Sergio Romero,...,0,0,0,0,0,0,0,0.5704770088195801,0.5704770088195801,1