# Data Basics Notebook
This notebook provides an introduction to working with both the Transfermarkt API
and UnderstatAPIs.

In [1]:
import duckdb
from understatapi import UnderstatClient
from matplotlib import pyplot as plt
import pandas as pd

## Transfermarkt API

In [3]:
# Example: Liverpool players from 2025
q = """
SELECT *
FROM read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/players.csv.gz') P
WHERE current_club_domestic_competition_id = 'GB1' AND last_season = 2025
AND P.current_club_id = 31
"""

duckdb.sql(q).show() # Run the query

┌───────────┬────────────┬──────────────┬─────────────────────┬─────────────┬─────────────────┬─────────────────────┬───────────────────────┬────────────────────┬────────────────────────┬─────────────────────┬────────────────────┬────────────┬─────────┬──────────────┬──────────────────────────┬───────────────────┬────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬─────────────────────────┬─────────────────────┬─────────────────────────────┐
│ player_id │ first_name │  last_name   │        name         │ last_season │ current_club_id │     player_code     │   country_of_birth    │   city_of_birth    │ country_of_citizenship │    date_of_birth    │    sub_position    │  position  │  foot   │ height_in_cm │ contract_expiration_date │    agent_name     │                                     image_url                                      │                                    url                                    │ current_club_domestic_competition_id │    current_club_name    │ market_value_in_eur │ highest_market_value_in_eur │
│   int64   │  varchar   │   varchar    │       varchar       │    int64    │      int64      │       varchar       │        varchar        │      varchar       │        varchar         │      timestamp      │      varchar       │  varchar   │ varchar │    int64     │        timestamp         │      varchar      │                                      varchar                                       │                                  varchar                                  │               varchar                │         varchar         │        int64        │            int64            │
├───────────┼────────────┼──────────────┼─────────────────────┼─────────────┼─────────────────┼─────────────────────┼───────────────────────┼────────────────────┼────────────────────────┼─────────────────────┼────────────────────┼────────────┼─────────┼──────────────┼──────────────────────────┼───────────────────┼────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼─────────────────────────┼─────────────────────┼─────────────────────────────┤
│    105470 │ NULL       │ Alisson      │ Alisson             │        2025 │              31 │ alisson             │ Brazil                │ Novo Hamburgo      │ Brazil                 │ 1992-10-02 00:00:00 │ Goalkeeper         │ Goalkeeper │ right   │          193 │ 2027-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/105470-1668522221.jpg?lm=1  │ https://www.transfermarkt.co.uk/alisson/profil/spieler/105470             │ GB1                                  │ Liverpool Football Club │            17000000 │                    90000000 │
│    139208 │ Virgil     │ van Dijk     │ Virgil van Dijk     │        2025 │              31 │ virgil-van-dijk     │ Netherlands           │ Breda              │ Netherlands            │ 1991-07-08 00:00:00 │ Centre-Back        │ Defender   │ right   │          195 │ 2027-06-30 00:00:00      │ ROOF              │ https://img.a.transfermarkt.technology/portrait/header/139208-1702049837.jpg?lm=1  │ https://www.transfermarkt.co.uk/virgil-van-dijk/profil/spieler/139208     │ GB1                                  │ Liverpool Football Club │            18000000 │                   100000000 │
│    146310 │ Wataru     │ Endo         │ Wataru Endo         │        2025 │              31 │ wataru-endo         │ Japan                 │ Yokohama, Kanagawa │ Japan                  │ 1993-02-09 00:00:00 │ Defensive Midfield │ Midfield   │ right   │          178 │ 2027-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/146310-1657181542.jpg?lm=1  │ https://www.transfermarkt.co.uk/wataru-endo/profil/spieler/146310         │ GB1                                  │ Liverpool Football Club │             5000000 │                    13000000 │
│    148455 │ Mohamed    │ Salah        │ Mohamed Salah       │        2025 │              31 │ mohamed-salah       │ Egypt                 │ Nagrig, Basyoun    │ Egypt                  │ 1992-06-15 00:00:00 │ Right Winger       │ Attack     │ left    │          175 │ 2027-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/148455-1727337594.jpg?lm=1  │ https://www.transfermarkt.co.uk/mohamed-salah/profil/spieler/148455       │ GB1                                  │ Liverpool Football Club │            30000000 │                   150000000 │
│    226049 │ Freddie    │ Woodman      │ Freddie Woodman     │        2025 │              31 │ freddie-woodman     │ England               │ London             │ England                │ 1997-03-04 00:00:00 │ Goalkeeper         │ Goalkeeper │ right   │          188 │ 2026-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/226049-1737883837.jpg?lm=1  │ https://www.transfermarkt.co.uk/freddie-woodman/profil/spieler/226049     │ GB1                                  │ Liverpool Football Club │             3000000 │                    10000000 │
│    256178 │ Joe        │ Gomez        │ Joe Gomez           │        2025 │              31 │ joe-gomez           │ England               │ London             │ England                │ 1997-05-23 00:00:00 │ Centre-Back        │ Defender   │ right   │          188 │ 2027-06-30 00:00:00      │ Wasserman         │ https://img.a.transfermarkt.technology/portrait/header/256178-1746645094.jpg?lm=1  │ https://www.transfermarkt.co.uk/joe-gomez/profil/spieler/256178           │ GB1                                  │ Liverpool Football Club │            15000000 │                    42000000 │
│    341092 │ Federico   │ Chiesa       │ Federico Chiesa     │        2025 │              31 │ federico-chiesa     │ Italy                 │ Genova             │ Italy                  │ 1997-10-25 00:00:00 │ Right Winger       │ Attack     │ right   │          175 │ 2028-06-30 00:00:00      │ LIAN Sports Group │ https://img.a.transfermarkt.technology/portrait/header/341092-1663576975.jpg?lm=1  │ https://www.transfermarkt.co.uk/federico-chiesa/profil/spieler/341092     │ GB1                                  │ Liverpool Football Club │            18000000 │                    65000000 │
│    357119 │ Ibrahima   │ Konaté       │ Ibrahima Konaté     │        2025 │              31 │ ibrahima-konate     │ France                │ Paris              │ France                 │ 1999-05-25 00:00:00 │ Centre-Back        │ Defender   │ right   │          194 │ 2026-06-30 00:00:00      │ CAA Stellar       │ https://img.a.transfermarkt.technology/portrait/header/357119-1669190550.jpg?lm=1  │ https://www.transfermarkt.co.uk/ibrahima-konate/profil/spieler/357119     │ GB1                                  │ Liverpool Football Club │            50000000 │                    50000000 │
│    433188 │ Curtis     │ Jones        │ Curtis Jones        │        2025 │              31 │ curtis-jones        │ England               │ Liverpool          │ England                │ 2001-01-30 00:00:00 │ Central Midfield   │ Midfield   │ right   │          185 │ 2027-06-30 00:00:00      │ Wasserman         │ https://img.a.transfermarkt.technology/portrait/header/433188-1701681163.jpg?lm=1  │ https://www.transfermarkt.co.uk/curtis-jones/profil/spieler/433188        │ GB1                                  │ Liverpool Football Club │            40000000 │                    40000000 │
│    434675 │ Cody       │ Gakpo        │ Cody Gakpo          │        2025 │              31 │ cody-gakpo          │ Netherlands           │ Eindhoven          │ Netherlands            │ 1999-05-07 00:00:00 │ Left Winger        │ Attack     │ right   │          193 │ 2030-06-30 00:00:00      │ SEG               │ https://img.a.transfermarkt.technology/portrait/header/434675-1682690965.jpg?lm=1  │ https://www.transfermarkt.co.uk/cody-gakpo/profil/spieler/434675          │ GB1                                  │ Liverpool Football Club │            70000000 │                    70000000 │
│       ·   │  ·         │   ·          │     ·               │          ·  │               · │     ·               │     ·                 │     ·              │     ·                  │          ·          │      ·             │   ·        │   ·     │           ·  │          ·               │  ·                │                                         ·                                          │                                ·                                          │  ·                                   │            ·            │                ·    │                        ·    │
│       ·   │  ·         │   ·          │     ·               │          ·  │               · │     ·               │     ·                 │     ·              │     ·                  │          ·          │      ·             │   ·        │   ·     │           ·  │          ·               │  ·                │                                         ·                                          │                                ·                                          │  ·                                   │            ·            │                ·    │                        ·    │
│       ·   │  ·         │   ·          │     ·               │          ·  │               · │     ·               │     ·                 │     ·              │     ·                  │          ·          │      ·             │   ·        │   ·     │           ·  │          ·               │  ·                │                                         ·                                          │                                ·                                          │  ·                                   │            ·            │                ·    │                        ·    │
│    534033 │ Alexis     │ Mac Allister │ Alexis Mac Allister │        2025 │              31 │ alexis-mac-allister │ Argentina             │ Santa Rosa         │ Argentina              │ 1998-12-24 00:00:00 │ Central Midfield   │ Midfield   │ right   │          176 │ 2028-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/534033-1669835342.jpg?lm=1  │ https://www.transfermarkt.co.uk/alexis-mac-allister/profil/spieler/534033 │ GB1                                  │ Liverpool Football Club │            85000000 │                    85000000 │
│    598577 │ Florian    │ Wirtz        │ Florian Wirtz       │        2025 │              31 │ florian-wirtz       │ Germany               │ Pulheim            │ Germany                │ 2003-05-03 00:00:00 │ Attacking Midfield │ Midfield   │ right   │          177 │ 2030-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/598577-1689710503.jpg?lm=1  │ https://www.transfermarkt.co.uk/florian-wirtz/profil/spieler/598577       │ GB1                                  │ Liverpool Football Club │           110000000 │                   140000000 │
│    624258 │ Conor      │ Bradley      │ Conor Bradley       │        2025 │              31 │ conor-bradley       │ Northern Ireland      │ Castlederg         │ Northern Ireland       │ 2003-07-09 00:00:00 │ Right-Back         │ Defender   │ right   │          181 │ 2029-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/624258-1762340233.jpg?lm=1  │ https://www.transfermarkt.co.uk/conor-bradley/profil/spieler/624258       │ GB1                                  │ Liverpool Football Club │            30000000 │                    30000000 │
│    633652 │ Calvin     │ Ramsay       │ Calvin Ramsay       │        2025 │              31 │ calvin-ramsay       │ Scotland              │ Aberdeen           │ Scotland               │ 2003-07-31 00:00:00 │ Right-Back         │ Defender   │ right   │          177 │ 2027-06-30 00:00:00      │ PLG               │ https://img.a.transfermarkt.technology/portrait/header/633652-1628698224.jpg?lm=1  │ https://www.transfermarkt.co.uk/calvin-ramsay/profil/spieler/633652       │ GB1                                  │ Liverpool Football Club │             5000000 │                     5000000 │
│    709726 │ Hugo       │ Ekitiké      │ Hugo Ekitiké        │        2025 │              31 │ hugo-ekitike        │ France                │ Reims              │ France                 │ 2002-06-20 00:00:00 │ Centre-Forward     │ Attack     │ right   │          190 │ 2031-06-30 00:00:00      │ OSA               │ https://img.a.transfermarkt.technology/portrait/header/709726-1758714741.jpg?lm=1  │ https://www.transfermarkt.co.uk/hugo-ekitike/profil/spieler/709726        │ GB1                                  │ Liverpool Football Club │            85000000 │                    85000000 │
│    730861 │ Milos      │ Kerkez       │ Milos Kerkez        │        2025 │              31 │ milos-kerkez        │ Serbia and Montenegro │ Vrbas              │ Hungary                │ 2003-11-07 00:00:00 │ Left-Back          │ Defender   │ left    │          180 │ 2030-06-30 00:00:00      │ LIAN Sports Group │ https://img.a.transfermarkt.technology/portrait/header/730861-1660762995.jpg?lm=1  │ https://www.transfermarkt.co.uk/milos-kerkez/profil/spieler/730861        │ GB1                                  │ Liverpool Football Club │            40000000 │                    40000000 │
│    864799 │ Stefan     │ Bajcetic     │ Stefan Bajcetic     │        2025 │              31 │ stefan-bajcetic     │ Spain                 │ Vigo               │ Spain                  │ 2004-10-22 00:00:00 │ Defensive Midfield │ Midfield   │ right   │          185 │ 2027-06-30 00:00:00      │ ROOF              │ https://img.a.transfermarkt.technology/portrait/header/864799-1661441233.jpg?lm=1  │ https://www.transfermarkt.co.uk/stefan-bajcetic/profil/spieler/864799     │ GB1                                  │ Liverpool Football Club │             7000000 │                     9000000 │
│   1045123 │ Trey       │ Nyoni        │ Trey Nyoni          │        2025 │              31 │ trey-nyoni          │ England               │ Leicester          │ England                │ 2007-06-30 00:00:00 │ Central Midfield   │ Midfield   │ right   │          180 │ 2026-06-30 00:00:00      │ SEG               │ https://img.a.transfermarkt.technology/portrait/header/1045123-1708933240.jpg?lm=1 │ https://www.transfermarkt.co.uk/trey-nyoni/profil/spieler/1045123         │ GB1                                  │ Liverpool Football Club │             6000000 │                     6000000 │
│   1086619 │ Giovanni   │ Leoni        │ Giovanni Leoni      │        2025 │              31 │ giovanni-leoni      │ Italy                 │ Roma               │ Italy                  │ 2006-12-21 00:00:00 │ Centre-Back        │ Defender   │ right   │          196 │ 2031-06-30 00:00:00      │ Excellence Sport  │ https://img.a.transfermarkt.technology/portrait/header/1086619-1751532399.jpg?lm=1 │ https://www.transfermarkt.co.uk/giovanni-leoni/profil/spieler/1086619     │ GB1                                  │ Liverpool Football Club │            25000000 │                    25000000 │
│   1108466 │ Rio        │ Ngumoha      │ Rio Ngumoha         │        2025 │              31 │ rio-ngumoha         │ England               │ London             │ England                │ 2008-08-29 00:00:00 │ Left Winger        │ Attack     │ right   │          170 │ 2028-06-30 00:00:00      │ NULL              │ https://img.a.transfermarkt.technology/portrait/header/1108466-1730834754.jpg?lm=1 │ https://www.transfermarkt.co.uk/rio-ngumoha/profil/spieler/1108466        │ GB1                                  │ Liverpool Football Club │            15000000 │                    15000000 │
├───────────┴────────────┴──────────────┴─────────────────────┴─────────────┴─────────────────┴─────────────────────┴───────────────────────┴────────────────────┴────────────────────────┴─────────────────────┴────────────────────┴────────────┴─────────┴──────────────┴──────────────────────────┴───────────────────┴────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────────────────────┴─────────────────────┴─────────────────────────────┤
│ 24 rows (20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 23 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
# Example: liverpool current player valuations over time

q = """
SELECT P.player_id, P.name, V.date, V.market_value_in_eur
FROM read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/players.csv.gz') P
JOIN read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/player_valuations.csv.gz') V ON P.player_id = V.player_id
WHERE current_club_domestic_competition_id = 'GB1' AND last_season = 2025
AND P.current_club_id = 31
ORDER BY P.player_id, V.date
"""

duckdb.sql(q).show() # Run the query

┌───────────┬─────────────────┬────────────┬─────────────────────┐
│ player_id │      name       │    date    │ market_value_in_eur │
│   int64   │     varchar     │    date    │        int64        │
├───────────┼─────────────────┼────────────┼─────────────────────┤
│    105470 │ Alisson         │ 2012-05-12 │              150000 │
│    105470 │ Alisson         │ 2012-08-02 │              150000 │
│    105470 │ Alisson         │ 2014-07-08 │              300000 │
│    105470 │ Alisson         │ 2015-01-02 │             1000000 │
│    105470 │ Alisson         │ 2015-11-09 │             3500000 │
│    105470 │ Alisson         │ 2017-02-01 │             7000000 │
│    105470 │ Alisson         │ 2017-08-06 │             7000000 │
│    105470 │ Alisson         │ 2018-07-06 │            60000000 │
│    105470 │ Alisson         │ 2019-10-12 │            90000000 │
│    105470 │ Alisson         │ 2020-08-04 │            72000000 │
│       ·   │    ·            │     ·      │                ·    │
│       ·   │    ·            │     ·      │                ·    │
│       ·   │    ·            │     ·      │                ·    │
│    730861 │ Milos Kerkez    │ 2023-09-10 │            18000000 │
│    730861 │ Milos Kerkez    │ 2025-09-12 │            40000000 │
│    864799 │ Stefan Bajcetic │ 2022-03-11 │             1000000 │
│    864799 │ Stefan Bajcetic │ 2025-09-06 │             9000000 │
│    864799 │ Stefan Bajcetic │ 2025-09-12 │             7000000 │
│   1045123 │ Trey Nyoni      │ 2025-09-12 │             6000000 │
│   1086619 │ Giovanni Leoni  │ 2023-01-07 │              100000 │
│   1086619 │ Giovanni Leoni  │ 2024-03-06 │             4500000 │
│   1086619 │ Giovanni Leoni  │ 2025-09-12 │            25000000 │
│   1108466 │ Rio Ngumoha     │ 2025-09-12 │            15000000 │
├───────────┴─────────────────┴────────────┴─────────────────────┤
│ 195 rows (20 shown)                                  4 columns │
└────────────────────────────────────────────────────────────────┘

In [5]:
# Example: Basic Performance Stats

q = """
SELECT *
FROM read_csv_auto('https://pub-e682421888d945d684bcae8890b0ec20.r2.dev/data/appearances.csv.gz') A
LIMIT 10
"""

duckdb.sql(q).show()

┌────────────────┬─────────┬───────────┬────────────────┬────────────────────────┬────────────┬──────────────────┬────────────────┬──────────────┬───────────┬───────┬─────────┬────────────────┐
│ appearance_id  │ game_id │ player_id │ player_club_id │ player_current_club_id │    date    │   player_name    │ competition_id │ yellow_cards │ red_cards │ goals │ assists │ minutes_played │
│    varchar     │  int64  │   int64   │     int64      │         int64          │    date    │     varchar      │    varchar     │    int64     │   int64   │ int64 │  int64  │     int64      │
├────────────────┼─────────┼───────────┼────────────────┼────────────────────────┼────────────┼──────────────────┼────────────────┼──────────────┼───────────┼───────┼─────────┼────────────────┤
│ 2231978_38004  │ 2231978 │     38004 │            853 │                    235 │ 2012-07-03 │ Aurélien Joachim │ CLQ            │            0 │         0 │     2 │       0 │             90 │
│ 2233748_79232  │ 2233748 │     79232 │           8841 │                   2698 │ 2012-07-05 │ Ruslan Abyshov   │ ELQ            │            0 │         0 │     0 │       0 │             90 │
│ 2234413_42792  │ 2234413 │     42792 │           6251 │                    465 │ 2012-07-05 │ Sander Puri      │ ELQ            │            0 │         0 │     0 │       0 │             45 │
│ 2234418_73333  │ 2234418 │     73333 │           1274 │                   6646 │ 2012-07-05 │ Vegar Hedenstad  │ ELQ            │            0 │         0 │     0 │       0 │             90 │
│ 2234421_122011 │ 2234421 │    122011 │            195 │                   3008 │ 2012-07-05 │ Markus Henriksen │ ELQ            │            0 │         0 │     0 │       1 │             90 │
│ 2234421_146889 │ 2234421 │    146889 │            195 │                   2778 │ 2012-07-05 │ Peter Ankersen   │ ELQ            │            1 │         0 │     0 │       0 │             90 │
│ 2235539_28716  │ 2235539 │     28716 │            282 │                   7185 │ 2012-07-05 │ Adi Adilovic     │ ELQ            │            0 │         0 │     0 │       0 │             90 │
│ 2235539_69445  │ 2235539 │     69445 │            282 │                  19771 │ 2012-07-05 │ Ivan Sesar       │ ELQ            │            1 │         0 │     0 │       1 │             90 │
│ 2235545_19409  │ 2235545 │     19409 │            317 │                    200 │ 2012-07-05 │ Willem Janssen   │ ELQ            │            0 │         0 │     0 │       0 │             45 │
│ 2235545_30003  │ 2235545 │     30003 │            317 │                    317 │ 2012-07-05 │ Wout Brama       │ ELQ            │            0 │         0 │     0 │       0 │             90 │
├────────────────┴─────────┴───────────┴────────────────┴────────────────────────┴────────────┴──────────────────┴────────────────┴──────────────┴───────────┴───────┴─────────┴────────────────┤
│ 10 rows                                                                                                                                                                            13 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## Understat API

In [2]:
# Create connection
understat = UnderstatClient()

In [5]:
# Get all player data for a league/season
epl_players = understat.league(league="EPL").get_player_data(season="2025")

# Make into a dataframe
player_df = pd.DataFrame(epl_players)

player_df.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,8260,Erling Haaland,29,2439,22,23.13693391531706,7,4.766327390447259,102,21,1,0,F S,Manchester City,19,20.092258475720882,26.238575093448162,4.129314249381423
1,13222,Thiago,31,2662,19,21.101609505712986,1,3.155416488647461,71,19,6,0,F S,Brentford,13,15.773427560925484,19.4751720353961,3.4934082627296448
2,11363,Antoine Semenyo,29,2597,15,11.201724836602807,4,3.091043023392558,68,32,6,0,F M,"Bournemouth,Manchester City",14,9.67938713915646,16.244873739778996,4.950852746143937
3,8272,João Pedro,31,2345,14,14.15835139900446,5,3.9609613977372646,63,28,4,0,F M S,Chelsea,14,14.15835139900446,17.67835896089673,4.659978250041604
4,501,Danny Welbeck,30,1832,12,10.899193301796913,0,1.8765279427170753,43,18,5,0,F S,Brighton,11,8.6156866569072,12.241745796054602,3.454270198009908

In [8]:
player_df.sort_values(by="time", ascending=False).head(20)

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
53,5304,Mikel Merino,21,977,4,4.551519326865673,3,2.2901399955153465,21,12,1,0,F M S,Arsenal,4,4.551519326865673,7.0440468192100525,3.1536439023911953
464,13150,Jack Fletcher,3,97,0,0.037386249750852585,0,0.11487564817070961,1,2,0,0,S,Manchester United,0,0.037386249750852585,0.26276974007487297,0.14789408445358276
212,9501,Fabio Carvalho,6,97,1,0.6895682029426098,0,0,2,0,0,0,M S,Brentford,1,0.6895682029426098,0.6895682029426098,0
294,5355,Jacob Bruun Larsen,23,965,0,1.3876315392553806,1,1.2826955989003181,16,11,0,0,F M S,Burnley,0,1.3876315392553806,4.335738031193614,2.199708631262183
389,10120,Conor Bradley,15,962,0,0.21982916723936796,1,1.1937107481062412,6,4,5,0,D S,Liverpool,0,0.21982916723936796,3.412436105310917,2.4054819140583277
468,13247,Ezra Mayers,6,96,0,0.10989412665367126,0,0.11634047329425812,1,2,0,0,S,West Ham,0,0.10989412665367126,0.39119094237685204,0.16495634242892265
246,13692,Rio Ngumoha,11,95,1,0.546236764639616,0,1.2886440493166447,3,9,0,0,S,Liverpool,1,0.546236764639616,2.188313815742731,0.3534329878166318
351,8489,Jorge Cuenca,14,948,0,0.050821494311094284,0,0.5158752724528313,1,3,5,0,D S,Fulham,0,0.050821494311094284,2.2441382743418217,2.2441382743418217
432,11808,Andrey Santos,22,946,0,1.7154290862381458,0,0.6522208489477634,8,7,4,0,M S,Chelsea,0,1.7154290862381458,5.09560789167881,3.811923023313284
407,10822,Wilson Odobert,24,946,0,2.460178238339722,2,1.9524234533309937,21,20,0,0,F M S,Tottenham,0,2.460178238339722,5.9682222586125135,2.8834201879799366
225,10770,Soungoutou Magassa,18,944,1,0.6193040320649743,0,0.7463846588507295,7,5,3,0,M S,West Ham,1,0.6193040320649743,2.4097342267632484,1.522645689547062
185,7078,Sean Longstaff,17,944,1,0.6963180564343929,2,2.4830981642007828,13,22,2,0,M S,Leeds,1,0.6963180564343929,2.797569300979376,1.7294726222753525
343,7943,Igor Julio,4,94,0,0,0,0.018099337816238403,0,1,0,0,D S,West Ham,0,0,0.06989672780036926,0.06989672780036926
134,9767,Habib Diarra,12,939,2,2.0937851537019014,0,0.15947006829082966,15,2,4,0,M S,Sunderland,1,1.3326163161545992,2.122412709519267,0.7199767213314772
164,934,Axel Tuanzebe,11,939,1,0.5582677125930786,0,0,2,0,1,0,D,Burnley,1,0.5582677125930786,2.4150575436651707,1.856789831072092
162,885,Kyle Walker-Peters,18,937,1,1.1882447563111782,0,0.22901761904358864,5,5,2,0,D S,West Ham,1,1.1882447563111782,3.0865802317857742,1.9071616008877754
461,13068,Morato,15,935,0,1.401793820783496,0,0.013815321959555149,4,1,4,0,D S,Nottingham Forest,0,1.401793820783496,2.6422858498990536,2.0910839401185513
198,8252,Nicolás Domínguez,18,915,1,0.7124216975644231,0,0.7514081094413996,15,9,1,0,M S,Nottingham Forest,1,0.7124216975644231,3.362470768392086,2.2724769935011864
419,11253,Mamadou Sarr,2,91,0,0.5694634318351746,0,0,1,0,0,0,D S,Chelsea,0,0.5694634318351746,0.23050860315561295,0.23050860315561295
478,13584,Harry Howell,3,91,0,0,0,0,0,0,0,0,M S,Brighton,0,0,0,0

In [9]:
# Look at all positions

player_df["position"].unique()

array(['F S', 'F M', 'F M S', 'M S', 'F', 'M', 'D M S', 'D S', 'D M', 'D',
       'D F M S', 'S', 'GK', 'GK S'], dtype=object)

In [11]:
# Get all match stats for a particular player - Erling Haaland
player_matches = understat.player(player='8260').get_match_data()

# Convert to dataframe
player_matches_df = pd.DataFrame(player_matches)

# Sort by date
player_matches_df = player_matches_df.sort_values(by="date")

player_matches_df.head()

,goals,shots,xG,time,position,h_team,a_team,h_goals,a_goals,date,id,season,roster_id,xA,assists,key_passes,npg,npxG,xGChain,xGBuildup
190,3,3,1.3227900266647339,33,Sub,Augsburg,Borussia Dortmund,3,5,2020-01-18,12562,2019,389276,0,0,0,3,1.3227900266647339,1.3459999561309814,0.023214099928736687
189,2,3,1.3333300352096558,23,Sub,Borussia Dortmund,FC Cologne,5,1,2020-01-24,12566,2019,389900,0,0,0,2,1.3333300352096558,1.3333300352096558,0
188,2,2,0.7829639911651611,77,FW,Borussia Dortmund,Union Berlin,5,0,2020-02-01,12574,2019,391067,0.06835760176181793,0,1,2,0.7829639911651611,0.7862169742584229,0.5620520114898682
187,0,2,0.10662200301885605,90,FW,Bayer Leverkusen,Borussia Dortmund,4,3,2020-02-08,12584,2019,392772,0,0,0,0,0.10662200301885605,0.422342985868454,0.3633730113506317
186,1,2,0.6940990090370178,80,FW,Borussia Dortmund,Eintracht Frankfurt,4,0,2020-02-14,12592,2019,393399,0.04634920135140419,0,1,1,0.6940990090370178,0.7866899967193604,0.046242501586675644

In [ ]:
# Get all player names and ids and save to csv for later use

leagues = ["EPL", "La_Liga", "Bundesliga", "Serie_A", "Ligue_1"]
seasons = list(range(2015, 2026))

id_to_name = {}
for league in leagues:
    for season in seasons:
        players = understat.league(league=league).get_player_data(season=str(season))
        for p in players:
            id_to_name[p["id"]] = p["player_name"]
            
id_names = pd.DataFrame({"player_id":id_to_name.keys(), "name":id_to_name.values()})
id_names.to_csv("../data/id_names.csv")